version: "3.7"

services:
  frontend:
    container_name: vite_app
    image: michiorework/test-passkeys-frontend
    restart: always
    networks:
      - webnet

  postgres:
    container_name: postgres_db
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    networks:
      - webnet
    depends_on:
      - api
      - postgres
      - frontend
      - pgadmin
  api:
    container_name: api_app
    image: michiorework/test-passkeys-backend
    environment:
      PORT: 3000
      SECRET: mycustomuselongsecret
      EXPIRATION: "60 days"
      RELYING_PARTY_NAME: "Deriv POC Passkeys"
      RELYING_PARTY_ID: localhost
      ORIGIN: http://localhost
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/backend?schema=public"
    networks:
      - webnet
    restart: always
    depends_on:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - webnet
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  webnet:
volumes:
  pgdata:
  pgadmin:
